version: "3.7"

services:
  db:
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  nats-streaming:
    image: nats-streaming
    ports:
      - "4222:4222"

  web:
    build:
      context: .
      dockerfile: ./deployments/Dockerfile
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - ./templates:/app/templates
    depends_on:
      - db
      - redis
      - nats-streaming

  nginx:
    build:
      context: .
      dockerfile: ./deployments/nginx/Dockerfile.nginx
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  pg_data: