FROM nginx:1.21

RUN rm /etc/nginx/conf.d/default.conf && \
    mkdir -p /etc/nginx/conf.d

RUN rm -rf /usr/share/nginx/html/*

COPY /deployments/nginx/nginx.conf /etc/nginx/conf.d/default.conf